# @package habitat.simulator.agents.rgb_head_agent_vis

defaults:
  - agent_base
  - /habitat/simulator/sim_sensors@sim_sensors.head_depth_sensor: head_rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.third_rgb_sensor: third_rgb_sensor