# @package _global_

defaults:
  - /benchmark/rearrange: rearrange_easy
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /habitat/simulator/sim_sensors@habitat_baselines.eval.extra_sim_sensors.third_rgb_sensor: third_rgb_sensor
  - _self_

habitat_baselines:
  verbose: False
  trainer_name: "ddppo"
  torch_gpu_id: 0
  tensorboard_dir: "tb"
  video_dir: "rearrange_experiments/rearrange_easy_no_place_3/video_dir"
  video_fps: 30
  video_render_views:
    - "third_rgb_sensor"
  test_episode_count: 50
  eval_ckpt_path_dir: "rearrange_experiments/rearrange_easy_no_place_3/checkpoint_folder"
  num_environments: 16
  writer_type: 'wb'
  checkpoint_folder: "rearrange_experiments/rearrange_easy_no_place_3/checkpoint_folder"
  num_updates: -1
  total_num_steps: 1_000_000_000
  log_interval: 10
  num_checkpoints: 100
  # Force PyTorch to be single threaded as
  # this improves performance considerably
  force_torch_single_threaded: True
  eval_keys_to_include_in_name: ['reward', 'force', 'success']

  wb:
      project_name: 'monolithic_policies_rearrange'
      run_name: 'rearrange_easy_no_place_3'
      group: 'rearrange_easy_no_place_3'

  eval:
    video_option: ["disk"]

  rl:
    policy:
      name: "PointNavResNetPolicy"
      action_distribution_type: "gaussian"
      action_dist:
       use_log_std: True
    ppo:
      # ppo params
      clip_param: 0.2
      ppo_epoch: 3
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.0001
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 128
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: False
      use_linear_lr_decay: False
      reward_window_size: 50

      use_normalized_advantage: False

      hidden_size: 768

      # Use double buffered sampling, typically helps
      # when environment time is similar or larger than
      # policy inference time during rollout generation
      use_double_buffered_sampler: False

    ddppo:
      sync_frac: 0.6
      # The PyTorch distributed backend to use
      distrib_backend: NCCL
      # Visual encoder backbone
      pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      # Initialize with pretrained weights
      pretrained: False
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: False
      # Whether the visual encoder backbone will be trained.
      train_encoder: True
      # Whether to reset the critic linear layer
      reset_critic: True

      # Model parameters
      backbone: resnet18
      rnn_type: LSTM
      num_recurrent_layers: 4
